# .travis.yml Execution script for role tests on Travis-CI
---
dist: xenial
sudo: required

env:
  global:
    - ANSIBLE_VERSION=2.9
  matrix:
    - DISTRIBUTION: centos
      VERSION: 7
    - DISTRIBUTION: ubuntu
      VERSION: 18.04

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install --only-upgrade git
  - |
    for i in docker-tests.sh functional-tests.sh ansible.cfg; do
      wget -O docker-tests/${i} https://raw.githubusercontent.com/open-io/ansible-role-openio-skeleton/docker-tests/${i}
    done
  - sudo pip install --upgrade pip
  - sudo pip install ansible-lint yamllint

script:
  # Lint
  # - ansible-lint . -x ANSIBLE0016
  - yamllint .

  # Create container and apply test playbook
  - ./docker-tests/docker-tests.sh

  # wait 30s for netdata to gather metrics
  - sleep 30

  # Run functional tests on the container
  - SUT_IP=172.17.0.2 SUT_ID=$(docker ps -qa) ./docker-tests/functional-tests.sh
...
