---
# Maybe just require the ansible-role-openio-sds ?
- name: RedHat| add OpenIO SDS repository
  yum:
    name: "{{ openio_sds_repository }}/el/openio-sds-release-{{ openio_release }}-1.el.noarch.rpm"
    state: present
...
